param([string]$ProjectRoot,[string]$RunRoot,[string]$Stamp)
$ErrorActionPreference='Stop'
$NL=[Environment]::NewLine
$StageName='V430PQ_STEAM_MATURE_LOOP_MANUAL_REFRESH_UI_STATUS_PAYLOAD_AUTHORIZATION_OR_HOLD'
$Status='READY_FOR_USER_APPROVAL_OF_V430PR_MANUAL_REFRESH_UI_READONLY_STATUS_PAYLOAD_BUILD_OR_HOLD'
$Decision=$Status
$LatestDir=Join-Path $ProjectRoot '11_SYSTEM_AUDIT_HANDOFF\99_AI_GENERATED_SYSTEM_INDEX'
$V430PPLatestPath=Join-Path $LatestDir 'v430pp_steam_mature_loop_manual_refresh_screening_review_or_hold_latest.json'
$V430PPReportPath=Join-Path $ProjectRoot '1071_V430PP_STEAM_MATURE_LOOP_MANUAL_REFRESH_SCREENING_REVIEW_OR_HOLD\V430PP_STEAM_MATURE_LOOP_MANUAL_REFRESH_SCREENING_REVIEW_OR_HOLD_20260521_162231\05_REPORT\v430pp_steam_mature_loop_manual_refresh_screening_review_or_hold_report.json'
$V430PPProofPath=Join-Path $ProjectRoot '1071_V430PP_STEAM_MATURE_LOOP_MANUAL_REFRESH_SCREENING_REVIEW_OR_HOLD\V430PP_STEAM_MATURE_LOOP_MANUAL_REFRESH_SCREENING_REVIEW_OR_HOLD_20260521_162231\04_BOUNDARY\no_fetch_no_ev_no_databridge_no_ui_no_buy_trade_proof.txt'
$PayloadCandidatePath=Join-Path $ProjectRoot '1071_V430PP_STEAM_MATURE_LOOP_MANUAL_REFRESH_SCREENING_REVIEW_OR_HOLD\V430PP_STEAM_MATURE_LOOP_MANUAL_REFRESH_SCREENING_REVIEW_OR_HOLD_20260521_162231\03_PAYLOAD\manual_refresh_ui_readonly_status_payload_candidate.json'
$V430PPLatestLoaded=Test-Path -LiteralPath $V430PPLatestPath
$V430PPReportLoaded=Test-Path -LiteralPath $V430PPReportPath
$V430PPProofLoaded=Test-Path -LiteralPath $V430PPProofPath
if(-not ($V430PPLatestLoaded -and $V430PPReportLoaded -and $V430PPProofLoaded -and (Test-Path -LiteralPath $PayloadCandidatePath))){ throw 'missing V430PP anchor or payload candidate' }
$AuthDir=Join-Path $RunRoot '01_AUTHORIZATION'; $RowsDir=Join-Path $RunRoot '02_ROWS'; $ProofDir=Join-Path $RunRoot '03_PROOF'; $ReportDir=Join-Path $RunRoot '04_REPORT'; $LatestCopyDir=Join-Path $RunRoot '05_LATEST_COPY'; $FootprintDir=Join-Path $RunRoot '06_FOOTPRINT'; $GitDir=Join-Path $RunRoot '07_GIT_FOOTPRINT'
@($AuthDir,$RowsDir,$ProofDir,$ReportDir,$LatestCopyDir,$FootprintDir,$GitDir) | ForEach-Object { New-Item -ItemType Directory -Force -Path $_ | Out-Null }
$RefreshSuccess=7; $PriceCandidate=7; $Blocked=0; $Errors=0; $ScreeningReady=0; $HoldOrReview=7; $UiStatusLabel='REVIEW_REQUIRED / PARTIAL_SCREENING'
$ApprovalPhrase='I APPROVE V430PR MANUAL_REFRESH_UI_READONLY_STATUS_PAYLOAD_BUILD_ONLY; BUILD A READONLY UI STATUS PAYLOAD FOR THE V430PO/V430PP MANUAL REFRESH RESULT SHOWING 7/7 REFRESH SUCCESS, 7 PRICE CANDIDATES, 0 BLOCKED, 0 ERRORS, 0 SCREENING_READY, 7 HOLD_OR_REVIEW, REVIEW_REQUIRED STATUS ONLY; NO LIVE UI PATCH, NO DATA_BRIDGE WRITE, NO ACTIVE_PAYLOAD WRITE, NO OFFICIAL EV, NO TRUSTED EV, NO STEAM FETCH, NO BUFF FETCH, NO BUY_NOW, NO TRADEUP_NOW, NO TRADE_OR_ORDER.'
$PacketPath=Join-Path $AuthDir 'manual_refresh_ui_status_payload_authorization_packet.md'
$PacketLines=@('# V430PQ Manual Refresh UI Status Payload Authorization Packet','','Stage: '+$StageName,'Status: '+$Status,'Decision: '+$Decision,'','This is an authorization-only packet for the next V430PR readonly UI status payload build. It does not authorize a LIVE UI patch, DATA_BRIDGE write, active payload write, EV calculation, Steam fetch, BUFF fetch, BUY_NOW, TRADEUP_NOW, trade, or order.','','## Required Truth','','The V430PO manual refresh succeeded for 7 of 7 frozen Steam Mature Loop targets. V430PP then reviewed the result and classified the package as partial: 7 price candidates were captured, 0 targets were blocked, 0 errors occurred, 0 rows are screening-ready, and 7 rows require hold/review.','','The future readonly status payload must show: REVIEW_REQUIRED / PARTIAL_SCREENING. It must not show READY_FOR_SIGNAL. It must not claim official EV or trusted EV. It must not present any trade action.','','## Allowed UI Text','','- Manual refresh succeeded','- 7 price candidates captured','- Screening review required','- 0 rows ready for signal','- 7 rows hold or review','- No trade action','','## Forbidden UI Text or Behavior','','- BUY_NOW','- TRADEUP_NOW','- trade/order action','- READY_FOR_SIGNAL','- official EV claim','- trusted EV claim','- DATA_BRIDGE write','- active payload write','- hidden fetch','','## Next Approval Phrase','','```text',$ApprovalPhrase,'```')
Set-Content -LiteralPath $PacketPath -Value ($PacketLines -join $NL) -Encoding UTF8
$ScopePath=Join-Path $RowsDir 'manual_refresh_ui_status_payload_scope_rows.csv'
@([pscustomobject]@{scope_item='payload_source';value=$PayloadCandidatePath;rule='reference_only_no_write'},[pscustomobject]@{scope_item='refresh_success_count';value=$RefreshSuccess;rule='display_as_success_count'},[pscustomobject]@{scope_item='price_candidate_count';value=$PriceCandidate;rule='display_as_candidates_captured'},[pscustomobject]@{scope_item='blocked_count';value=$Blocked;rule='display_zero'},[pscustomobject]@{scope_item='error_count';value=$Errors;rule='display_zero'},[pscustomobject]@{scope_item='screening_ready_count';value=$ScreeningReady;rule='display_zero_ready_for_signal'},[pscustomobject]@{scope_item='hold_or_review_count';value=$HoldOrReview;rule='display_review_required'},[pscustomobject]@{scope_item='ui_status_label';value=$UiStatusLabel;rule='must_not_be_ready_for_signal'}) | Export-Csv -LiteralPath $ScopePath -NoTypeInformation -Encoding UTF8
$TruthPath=Join-Path $RowsDir 'manual_refresh_ui_status_truth_table.csv'
@([pscustomobject]@{field='refresh_success_count';value='7';required_display='7 of 7 refresh success';prohibited_display='failed refresh'},[pscustomobject]@{field='price_candidate_count';value='7';required_display='7 price candidates captured';prohibited_display='EV ready'},[pscustomobject]@{field='blocked_count';value='0';required_display='0 blocked';prohibited_display='bypass allowed'},[pscustomobject]@{field='error_count';value='0';required_display='0 errors';prohibited_display='ready signal'},[pscustomobject]@{field='screening_ready_count';value='0';required_display='0 rows ready for signal';prohibited_display='ready for signal'},[pscustomobject]@{field='hold_or_review_count';value='7';required_display='7 hold or review';prohibited_display='auto handoff'},[pscustomobject]@{field='status';value=$UiStatusLabel;required_display='review required partial screening';prohibited_display='official or trusted EV'}) | Export-Csv -LiteralPath $TruthPath -NoTypeInformation -Encoding UTF8
$AllowedPath=Join-Path $RowsDir 'manual_refresh_ui_allowed_forbidden_matrix.csv'
@([pscustomobject]@{item='Manual refresh succeeded';allowed='true';forbidden='false';note='readonly status'},[pscustomobject]@{item='7 price candidates captured';allowed='true';forbidden='false';note='candidate count only'},[pscustomobject]@{item='Screening review required';allowed='true';forbidden='false';note='required truth'},[pscustomobject]@{item='0 rows ready for signal';allowed='true';forbidden='false';note='must be explicit'},[pscustomobject]@{item='No trade action';allowed='true';forbidden='false';note='boundary'},[pscustomobject]@{item='BUY_NOW';allowed='false';forbidden='true';note='forbidden'},[pscustomobject]@{item='TRADEUP_NOW';allowed='false';forbidden='true';note='forbidden'},[pscustomobject]@{item='Trade/order action';allowed='false';forbidden='true';note='forbidden'},[pscustomobject]@{item='Official EV / Trusted EV claim';allowed='false';forbidden='true';note='no EV authorized'},[pscustomobject]@{item='DATA_BRIDGE or active payload write';allowed='false';forbidden='true';note='not authorized'}) | Export-Csv -LiteralPath $AllowedPath -NoTypeInformation -Encoding UTF8
$DisplayPath=Join-Path $RowsDir 'manual_refresh_ui_status_display_text_plan.csv'
@([pscustomobject]@{display_field='headline';text='Manual refresh succeeded';required='true'},[pscustomobject]@{display_field='candidate_count';text='7 price candidates captured';required='true'},[pscustomobject]@{display_field='screening_status';text='Screening review required';required='true'},[pscustomobject]@{display_field='ready_count';text='0 rows ready for signal';required='true'},[pscustomobject]@{display_field='review_count';text='7 rows hold or review';required='true'},[pscustomobject]@{display_field='boundary';text='No trade action';required='true'}) | Export-Csv -LiteralPath $DisplayPath -NoTypeInformation -Encoding UTF8
$ReferencePath=Join-Path $RowsDir 'manual_refresh_ui_status_payload_reference_rows.csv'
@([pscustomobject]@{reference='v430pp_payload_candidate';path=$PayloadCandidatePath;loaded='true';role='readonly payload source candidate'},[pscustomobject]@{reference='v430pp_latest';path=$V430PPLatestPath;loaded=$V430PPLatestLoaded;role='anchor'},[pscustomobject]@{reference='v430pp_report';path=$V430PPReportPath;loaded=$V430PPReportLoaded;role='report'},[pscustomobject]@{reference='v430pp_proof';path=$V430PPProofPath;loaded=$V430PPProofLoaded;role='boundary proof'}) | Export-Csv -LiteralPath $ReferencePath -NoTypeInformation -Encoding UTF8
$PhrasePath=Join-Path $AuthDir 'manual_refresh_ui_status_draft_user_approval_phrase.txt'; Set-Content -LiteralPath $PhrasePath -Value $ApprovalPhrase -Encoding UTF8
$ProofPath=Join-Path $ProofDir 'no_ui_patch_no_databridge_no_ev_no_fetch_no_buy_trade_proof.txt'
Set-Content -LiteralPath $ProofPath -Value ('V430PQ proof'+$NL+'authorization_only=true'+$NL+'live_ui_patched=false'+$NL+'data_bridge_write=false'+$NL+'active_payload_write=false'+$NL+'official_ev_calculated=false'+$NL+'trusted_ev_calculated=false'+$NL+'steam_fetch_executed=false'+$NL+'buff_fetch_executed=false'+$NL+'buy_now=false'+$NL+'tradeup_now=false'+$NL+'trade_or_order=false'+$NL+'faictory_touched=false') -Encoding UTF8
$FootprintPath=Join-Path (Join-Path $ProjectRoot 'words.cossp') ('V430PQ_MANUAL_REFRESH_UI_STATUS_PAYLOAD_AUTHORIZATION_FOOTPRINT_' + $Stamp + '.md')
Set-Content -LiteralPath $FootprintPath -Value ('# V430PQ Local Footprint'+$NL+$NL+'Authorization-only stage for partial manual refresh UI readonly status payload. Refresh succeeded 7/7, price candidates captured 7, blocked 0, errors 0, screening ready 0, hold or review 7. UI label must be REVIEW_REQUIRED / PARTIAL_SCREENING. No UI patch, DATA_BRIDGE write, active payload write, EV calculation, fetch, BUY_NOW, TRADEUP_NOW, or trade/order occurred.') -Encoding UTF8
$ReportPath=Join-Path $ReportDir 'v430pq_steam_mature_loop_manual_refresh_ui_status_payload_authorization_or_hold_report.json'
$LatestPath=Join-Path $LatestDir 'v430pq_steam_mature_loop_manual_refresh_ui_status_payload_authorization_or_hold_latest.json'
$LatestCopyPath=Join-Path $LatestCopyDir 'v430pq_steam_mature_loop_manual_refresh_ui_status_payload_authorization_or_hold_latest.json'
$GitRawPath=Join-Path $GitDir 'v430pq_manual_refresh_ui_status_payload_authorization_git_raw_footprint.txt'
$GitSummaryPath=Join-Path $GitDir 'v430pq_manual_refresh_ui_status_payload_authorization_git_summary.md'
$ScriptPath=Join-Path (Join-Path $RunRoot '00_EXECUTED_SCRIPT') 'RUN_V430PQ_AUTH_FINAL.ps1'
$ScriptHash=(Get-FileHash -LiteralPath $ScriptPath -Algorithm SHA256).Hash.ToLower()
$ReportObj=[ordered]@{status=$Status;decision=$Decision;project_root_confirmed=$ProjectRoot;faictory_touched=$false;v430pp_latest_loaded=$V430PPLatestLoaded;v430pp_report_loaded=$V430PPReportLoaded;v430pp_proof_loaded=$V430PPProofLoaded;manual_refresh_ui_status_payload_authorization_packet_created=$true;refresh_success_count=$RefreshSuccess;price_candidate_count=$PriceCandidate;blocked_count=$Blocked;error_count=$Errors;screening_ready_count=$ScreeningReady;hold_or_review_count=$HoldOrReview;ui_status_label=$UiStatusLabel;ui_status_truth_table_created=$true;ui_allowed_forbidden_matrix_created=$true;ready_for_user_approval_of_manual_refresh_ui_status_payload_build=$true;live_ui_patched=$false;data_bridge_write=$false;active_payload_write=$false;official_ev_calculated=$false;trusted_ev_calculated=$false;steam_fetch_executed=$false;buff_fetch_executed=$false;buy_now=$false;tradeup_now=$false;trade_or_order=$false;git_repo_used=$true;git_commit_succeeded=$false;git_push_succeeded=$false;git_push_failure_note='pending';head_matches_origin=$false;worktree_clean=$false;manual_refresh_ui_status_authorization_packet=$PacketPath;manual_refresh_ui_status_approval_phrase=$PhrasePath;report_json=$ReportPath;latest_json=$LatestPath;proof=$ProofPath;footprint=$FootprintPath;git_raw_footprint=$GitRawPath;git_summary=$GitSummaryPath;executed_script_path=$ScriptPath;executed_script_sha256=$ScriptHash;next_safe_step='USER_APPROVAL_OF_V430PR_MANUAL_REFRESH_UI_READONLY_STATUS_PAYLOAD_BUILD_OR_HOLD'}
$ReportObj | ConvertTo-Json -Depth 6 | Set-Content -LiteralPath $ReportPath -Encoding UTF8
$ReportObj | ConvertTo-Json -Depth 6 | Set-Content -LiteralPath $LatestPath -Encoding UTF8
Copy-Item -LiteralPath $LatestPath -Destination $LatestCopyPath -Force
Set-Content -LiteralPath $GitRawPath -Value ('V430PQ git raw footprint'+$NL+'stage='+$StageName+$NL+'status='+$Status+$NL+'decision='+$Decision+$NL+'script='+$ScriptPath+$NL+'script_sha256='+$ScriptHash+$NL+'safety=no_ui_patch_no_databridge_no_ev_no_fetch_no_buy_trade') -Encoding UTF8
Set-Content -LiteralPath $GitSummaryPath -Value ('# V430PQ Git Summary'+$NL+$NL+'Stage: '+$StageName+$NL+'Status: '+$Status+$NL+'Decision: '+$Decision+$NL+'Latest JSON: '+$LatestPath+$NL+'Report JSON: '+$ReportPath+$NL+'Executed script: '+$ScriptPath+$NL+'Executed script SHA256: '+$ScriptHash+$NL+$NL+'Safety: authorization-only; no UI patch, DATA_BRIDGE, active payload, EV, fetch, BUY_NOW, TRADEUP_NOW, or trade/order.') -Encoding UTF8
$GitRepo=Join-Path $ProjectRoot '00_GITHUB_FOOTPRINTS\pycson-footprints'
$MirrorRoot=Join-Path $GitRepo ('stage_mirror\V430PQ_' + $Stamp); New-Item -ItemType Directory -Force -Path $MirrorRoot | Out-Null
@($PacketPath,$ScopePath,$TruthPath,$AllowedPath,$DisplayPath,$ReferencePath,$PhrasePath,$ProofPath,$ReportPath,$LatestPath,$FootprintPath,$GitRawPath,$GitSummaryPath,$ScriptPath) | ForEach-Object { Copy-Item -LiteralPath $_ -Destination (Join-Path $MirrorRoot (Split-Path -Leaf $_)) -Force }
$VersionDir=Join-Path $GitRepo 'version_summaries\V430PQ'; New-Item -ItemType Directory -Force -Path $VersionDir | Out-Null
$VersionSummary=Join-Path $VersionDir ('v430pq_manual_refresh_ui_status_payload_authorization_' + $Stamp + '.md')
Set-Content -LiteralPath $VersionSummary -Value ('# V430PQ Version Summary'+$NL+$NL+'Authorization-only packet for partial manual refresh UI readonly status payload. Truth: 7 refresh successes, 7 candidates, 0 blocked, 0 errors, 0 screening-ready, 7 hold/review. Status must be REVIEW_REQUIRED / PARTIAL_SCREENING.') -Encoding UTF8
$RawDir=Join-Path $GitRepo 'raw_footprints_archive\V430PQ'; New-Item -ItemType Directory -Force -Path $RawDir | Out-Null
Copy-Item -LiteralPath $FootprintPath -Destination (Join-Path $RawDir (Split-Path -Leaf $FootprintPath)) -Force
$GitSummDir=Join-Path $GitRepo 'git_summaries\V430PQ'; New-Item -ItemType Directory -Force -Path $GitSummDir | Out-Null
Copy-Item -LiteralPath $GitSummaryPath -Destination (Join-Path $GitSummDir (Split-Path -Leaf $GitSummaryPath)) -Force
[ordered]@{run_root=$RunRoot;report=$ReportPath;latest=$LatestPath;proof=$ProofPath;packet=$PacketPath;phrase=$PhrasePath;footprint=$FootprintPath;git_raw=$GitRawPath;git_summary=$GitSummaryPath;mirror=$MirrorRoot;version_summary=$VersionSummary} | ConvertTo-Json -Depth 4
